apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: blackbox-exporter
  endpoints:
    - port: http
      path: /probe
      interval: 30s
      scrapeTimeout: 10s
      params:
        module:
          - http_2xx
        target:
          - https://sretech.org
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
        - sourceLabels: [__param_target]
          targetLabel: target
        - sourceLabels: [__param_module]
          targetLabel: module
        - targetLabel: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
        - sourceLabels: [__param_target]
          targetLabel: __param_target
        - sourceLabels: [__param_module]
          targetLabel: __param_module
    - port: http
      path: /probe
      interval: 30s
      scrapeTimeout: 10s
      params:
        module:
          - http_2xx
        target:
          - https://usadaconnect.usada.org
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
        - sourceLabels: [__param_target]
          targetLabel: target
        - sourceLabels: [__param_module]
          targetLabel: module
        - targetLabel: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
        - sourceLabels: [__param_target]
          targetLabel: __param_target
        - sourceLabels: [__param_module]
          targetLabel: __param_module